### ISSUE TITLE
nltk.downloader punkt not installing

### ISSUE THREAD

**Issue by MallikarjunNamagiri** [mdrijwan123/Deployement-of-NLP-Model#2]
Hello, 

When i am trying to setup the docker environment in my ubuntu os, getting the error at the stage of the below line.

RUN python -m nltk.downloader punkt

**error :** 
ERROR: Command errored out with exit status 1: /usr/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i16mm35a/regex/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i16mm35a/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-p6289xw3/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.7m/regex Check the logs for full command output.

Regards,
Mallikarjun.N

**Comment by mdrijwan123** [comment]
Hi the requirement have been solved in latest code changes. Please check.
